export const UPDATE_AUTH = 'UPDATE_AUTH';
export const SHOW_ISSUE_DETAILS = 'SHOW_ISSUE_DETAILS';
export const DISPLAY_ISSUE_MODAL = 'DISPLAY_ISSUE_MODAL';
export const SET_SELECTED_ISSUE = 'SET_SELECTED_ISSUE';
export const CLOSE_ISSUE_MODAL = 'CLOSE_ISSUE_MODAL';
export const SET_KANBAN_DATA = 'SET_KANBAN_DATA';
